# Site settings
title: The Awesome Site2
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome site. Know that this is going to change the world. Just you wait.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://him2him2.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  him2him2

# Build settings
markdown: kramdown
